### PR TITLE
Adds example of typescirpt usage with notes on key snags

### PR DESCRIPTION
**Pull request by chris-schmitz**
I wanted to use this tool in a project I'm writing in typescript, but ran into a couple of snags. The snags were all just implementation details that I was able to figure out, so I thought I would add in a typescript example calling out the snags and how to fix them. 

After these changes I was able to write a test to make sure all of the types in my .env file were being parsed correctly (I pulled in your tool after having a couple of unexpected fails when casting the string values to their actual types manually).

Screen Shot 2020-09-02 at 12 13 16 PM

### CODE REVIEW

**Comment by niftylettuce** [comment]
Sorry but I don't and will not support TypeScript on any of my projects.

**Comment by chris-schmitz** [comment]
Ah, gotcha. 

Def your prerogative, though I would ask that you consider adding the note to the readme if nothing else so that other people who do want to use your module and happen to be using typescript have a head's up on how to address the implementation details in their code. 

I totally understand not wanting to support typescript, but the note isn't for your codebase, it's for other devs' codebases. That said, if you still don't want to add the note then all good, def your choice.

**Comment by niftylettuce** [comment]
Yeah, I don't even want to add any mention of the word TypeScript

**Comment by chris-schmitz** [comment]
All good. Well, thanks for writing and maintaining the tool. I appreciate the effort!

**Pull request closed without merging**
